### Imputation

* It is a preprocessing technique which handles missing values with the help of strategy parameter.

strategy : mean  |  median  |  most_frequent  | constant

For numerical column : mean and median
For categorical column : most frequent

constant - numerical : 0
           categorical: value

while using the constant strategy we should provide fill_value

In [60]:
# # SYNTAX
# from sklearn.impute import SimpleImputer

# impute =  SimpleImputer(strategy = 'constant' , fill_value = 0 | "unknown")

# impute.fit_transform(Xtrain)

In [61]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [25, 30, None, 45, 28, np.nan, 35, 40, 32, 27,25, 30, np.nan,28, np.nan, 35,30, np.nan,28, np.nan],
    "Salary": [40000, np.nan, 50000, 65000, 42000, 48000, np.nan, 70000, 52000, 45000,40000, np.nan, 50000,48000, np.nan, 70000, 52000,45000,40000, np.nan],
    "Department": [
        "HR",
        "IT",
        "Finance",
        np.nan,
        "IT",
        "HR",
        "Finance",
        np.nan,
        "IT",
        "HR",
        np.nan,
        "IT",
        "HR",
        "Finance",
        np.nan,
        "IT",
        "HR",
        "Finance",
        np.nan,
        "IT",
    ]
})

print(df)

     Age   Salary Department
0   25.0  40000.0         HR
1   30.0      NaN         IT
2    NaN  50000.0    Finance
3   45.0  65000.0        NaN
4   28.0  42000.0         IT
5    NaN  48000.0         HR
6   35.0      NaN    Finance
7   40.0  70000.0        NaN
8   32.0  52000.0         IT
9   27.0  45000.0         HR
10  25.0  40000.0        NaN
11  30.0      NaN         IT
12   NaN  50000.0         HR
13  28.0  48000.0    Finance
14   NaN      NaN        NaN
15  35.0  70000.0         IT
16  30.0  52000.0         HR
17   NaN  45000.0    Finance
18  28.0  40000.0        NaN
19   NaN      NaN         IT


In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Age         14 non-null     float64
 1   Salary      15 non-null     float64
 2   Department  15 non-null     object 
dtypes: float64(2), object(1)
memory usage: 612.0+ bytes


In [63]:
df.isnull().sum()

Age           6
Salary        5
Department    5
dtype: int64

In [64]:
from sklearn.impute import SimpleImputer

In [65]:
impute = SimpleImputer(strategy='constant',fill_value='unknown')
impute.fit_transform(df)


array([[25.0, 40000.0, 'HR'],
       [30.0, 'unknown', 'IT'],
       ['unknown', 50000.0, 'Finance'],
       [45.0, 65000.0, 'unknown'],
       [28.0, 42000.0, 'IT'],
       ['unknown', 48000.0, 'HR'],
       [35.0, 'unknown', 'Finance'],
       [40.0, 70000.0, 'unknown'],
       [32.0, 52000.0, 'IT'],
       [27.0, 45000.0, 'HR'],
       [25.0, 40000.0, 'unknown'],
       [30.0, 'unknown', 'IT'],
       ['unknown', 50000.0, 'HR'],
       [28.0, 48000.0, 'Finance'],
       ['unknown', 'unknown', 'unknown'],
       [35.0, 70000.0, 'IT'],
       [30.0, 52000.0, 'HR'],
       ['unknown', 45000.0, 'Finance'],
       [28.0, 40000.0, 'unknown'],
       ['unknown', 'unknown', 'IT']], dtype=object)

In [66]:
impute = SimpleImputer(strategy='mean')
impute.fit_transform(df[['Age','Salary']])

array([[2.50000000e+01, 4.00000000e+04],
       [3.00000000e+01, 5.04666667e+04],
       [3.12857143e+01, 5.00000000e+04],
       [4.50000000e+01, 6.50000000e+04],
       [2.80000000e+01, 4.20000000e+04],
       [3.12857143e+01, 4.80000000e+04],
       [3.50000000e+01, 5.04666667e+04],
       [4.00000000e+01, 7.00000000e+04],
       [3.20000000e+01, 5.20000000e+04],
       [2.70000000e+01, 4.50000000e+04],
       [2.50000000e+01, 4.00000000e+04],
       [3.00000000e+01, 5.04666667e+04],
       [3.12857143e+01, 5.00000000e+04],
       [2.80000000e+01, 4.80000000e+04],
       [3.12857143e+01, 5.04666667e+04],
       [3.50000000e+01, 7.00000000e+04],
       [3.00000000e+01, 5.20000000e+04],
       [3.12857143e+01, 4.50000000e+04],
       [2.80000000e+01, 4.00000000e+04],
       [3.12857143e+01, 5.04666667e+04]])

In [67]:
impute = SimpleImputer(strategy='median')
impute.fit_transform(df[['Age','Salary']])

array([[2.5e+01, 4.0e+04],
       [3.0e+01, 4.8e+04],
       [3.0e+01, 5.0e+04],
       [4.5e+01, 6.5e+04],
       [2.8e+01, 4.2e+04],
       [3.0e+01, 4.8e+04],
       [3.5e+01, 4.8e+04],
       [4.0e+01, 7.0e+04],
       [3.2e+01, 5.2e+04],
       [2.7e+01, 4.5e+04],
       [2.5e+01, 4.0e+04],
       [3.0e+01, 4.8e+04],
       [3.0e+01, 5.0e+04],
       [2.8e+01, 4.8e+04],
       [3.0e+01, 4.8e+04],
       [3.5e+01, 7.0e+04],
       [3.0e+01, 5.2e+04],
       [3.0e+01, 4.5e+04],
       [2.8e+01, 4.0e+04],
       [3.0e+01, 4.8e+04]])

In [68]:
impute = SimpleImputer(strategy='most_frequent')
impute.fit_transform(df[['Department']])

array([['HR'],
       ['IT'],
       ['Finance'],
       ['IT'],
       ['IT'],
       ['HR'],
       ['Finance'],
       ['IT'],
       ['IT'],
       ['HR'],
       ['IT'],
       ['IT'],
       ['HR'],
       ['Finance'],
       ['IT'],
       ['IT'],
       ['HR'],
       ['Finance'],
       ['IT'],
       ['IT']], dtype=object)